version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nextcloudpassword
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloudpassword

  nextcloud:
    image: nextcloud:latest
    restart: always
    depends_on:
      - mariadb
    volumes:
      - nextcloud-data:/var/www/html
    environment:
      VIRTUAL_HOST: nextcloud.example.com
      VIRTUAL_PORT: 443
      MYSQL_HOST: mariadb
      MYSQL_PORT: 3306
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloudpassword

volumes:
  nextcloud-data:
